"""add warehouse support

Revision ID: 0bd66b1b03e4
Revises: a9b855a149c1
Create Date: 2026-09-20 11:45:05.541023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd66b1b03e4'
down_revision: Union[str, Sequence[str], None] = 'a9b855a149c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_warehouses_sort_order_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_warehouses_name')
    )
    with op.batch_alter_table('products') as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_index(
            op.f('ix_products_warehouse_id'), ['warehouse_id'], unique=False
        )
        batch_op.create_foreign_key(
            'fk_products_warehouse_id_warehouses',
            'warehouses',
            ['warehouse_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_constraint(
            'fk_products_warehouse_id_warehouses', type_='foreignkey'
        )
        batch_op.drop_index(op.f('ix_products_warehouse_id'))
        batch_op.drop_column('warehouse_id')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
