"""create products table

Revision ID: b55c51380ce3
Revises: 
Create Date: 2026-09-19 17:49:20.159294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55c51380ce3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('size', sa.String(length=200), nullable=False),
    sa.Column('packing_qty', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('carton_count', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("unit IN ('pcs', 'set')", name='ck_products_unit_valid'),
    sa.CheckConstraint('carton_count >= 0', name='ck_products_carton_count_nonnegative'),
    sa.CheckConstraint('packing_qty > 0', name='ck_products_packing_qty_positive'),
    sa.CheckConstraint('price >= 0', name='ck_products_price_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
